theme: jekyll-theme-architect
title: Mizukoshi Keita
show_downloads: true
google_analytics:

gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed

markdown:    redcarpet
